import 'package:hive/hive.dart';

// dart run build_runner build
part 'setup_printout_model.g.dart'; // This will be generated by build_runner

@HiveType(typeId: 1)
class SetupPrintOut extends HiveObject {
  @HiveField(0)
  final String layout;
  @HiveField(1)
  final String footerColor;
  @HiveField(2)
  final String headerColor;
  @HiveField(3)
  final List<String> paletteColor;
  @HiveField(4)
  final String? companyLogo;
  @HiveField(5)
  final String? companyName;
  @HiveField(6)
  final String? companyEmail;
  @HiveField(7)
  final String? companyPhone;
  @HiveField(8)
  final String? companyAddress;
  @HiveField(9)
  final String? companyFax;
  @HiveField(10)
  final double? bodyFontSize;
  @HiveField(11)
  final double? tableFontSize;
  @HiveField(12)
  final double? subHeaderFontSize;
  @HiveField(13)
  final double? headerFontSize;

  SetupPrintOut({
    this.layout = 'dense',
    this.footerColor = '#ff2196f3',
    this.headerColor = '#ff4caf50',
    this.paletteColor = const [],
    this.companyLogo,
    this.companyName,
    this.companyEmail,
    this.companyPhone,
    this.companyAddress,
    this.companyFax,
    this.bodyFontSize = 11.0,
    this.tableFontSize = 10.0,
    this.headerFontSize = 12.0,
    this.subHeaderFontSize = 13.0,
  });

  /// A singleton instance representing an empty/default SetupPrintOut.
  /// Used as a fallback when no matching SetupPrintOut is found.
  static final empty = SetupPrintOut();

  /// Returns true if this instance is the singleton [empty] SetupPrintOut.
  /// Use this to check if the SetupPrintOut is the default/fallback (e.g., not found).
  bool get isEmpty => identical(this, SetupPrintOut.empty);

  bool get isNotEmpty => !isEmpty;

  // Check for empty layout
  bool get isLayoutEmpty => layout == '';

  // Check for empty colors fields
  bool get isColorsEmpty =>
      (paletteColor.isEmpty || paletteColor.contains('[]')) &&
      headerColor == '' &&
      footerColor == '';

  String get asString =>
      '$layout -> $paletteColor -> $headerColor -> $footerColor';

  SetupPrintOut copyWith({
    String? layout,
    String? headerColor,
    String? footerColor,
    List<String>? paletteColor,
    String? companyLogo,
    String? companyName,
    String? companyEmail,
    String? companyPhone,
    String? companyAddress,
    String? companyFax,
    double? headerFontSize,
    double? bodyFontSize,
    double? subHeaderFontSize,
    double? tableFontSize,
  }) => SetupPrintOut(
    layout: layout ?? this.layout,
    headerColor: headerColor ?? this.headerColor,
    footerColor: footerColor ?? this.footerColor,
    paletteColor: paletteColor ?? this.paletteColor,
    companyLogo: companyLogo ?? this.companyLogo,
    companyName: companyName ?? this.companyName,
    companyEmail: companyEmail ?? this.companyEmail,
    companyPhone: companyPhone ?? this.companyPhone,
    companyAddress: companyAddress ?? this.companyAddress,
    companyFax: companyFax ?? this.companyFax,
    headerFontSize: headerFontSize ?? this.headerFontSize,
    bodyFontSize: bodyFontSize ?? this.bodyFontSize,
    subHeaderFontSize: subHeaderFontSize ?? this.subHeaderFontSize,
    tableFontSize: tableFontSize ?? this.tableFontSize,
  );
}

/* // Check for all empty fields
  bool get isEmpty =>
      layout == '' &&
      (paletteColor.isEmpty || paletteColor.contains('[]')) &&
      headerColor == '' &&
      footerColor == '' &&
      companyLogo == '';

  bool get isNotEmpty => !isEmpty;*/
