/// HIVE BOX CACHE NAMES
// Base Directory path for app-level cache files related to ERP assignment
const appCacheDirectory = 'loc_os_third_as_dir';

// Caches device information such as model, OS version, and unique identifiers
const deviceInfoCache = 'uos_device_info_cache_db';

// Stores the list of backup file names used or generated by the app
const backupFileNamesCache = 'backup_file_name_cache_db';

// Cache reference master user's choice
const refMasterCache = 'ref_master_cache_db';

// Caches authenticated user credentials or ERP session info
const userAuthCache = 'os_auth_as_sign_erp_cache_db';

// Stores printout setup configuration like page layout or print preferences
const printoutSetupCache = 'setup_print_out_cache_db';

// Logs app errors or crash-related data for debugging
const appErrorLogsCache = 'app_error_logs_cache_db';

/// FIREBASE DATABASE COLLECTION PATH NAMES & HIVE BOX CACHE NAMES

// ---------------------------
// 🔐 Authentication Collections Path
// ---------------------------

// workspace user authentication records
const workspaceAccDBColPath = 'workspace_auth_db';
// Logs workspace signIn/signOut sessions for tracking and analytics
const workspaceSessionLogsColPath = 'workspace_session_logs';

// ---------------------------
// 💰 Subscription Licenses Collections Path
// ---------------------------

// Subscription Licenses
const subscriptionDBColPath = 'subscription_licenses_db';

// ---------------------------
// 🔐 Roles Collections Path
// ---------------------------

// Employee's roles and permissions
const rolesDBColPath = 'roles_db';

// ---------------------------
// 📦 Inventory Management System (IMS) Collections Path
// ---------------------------

/// Master-Data
const itemMasterDBColPath = 'item_master_data';
// Warehouse Facilities (Represents a physical storage place)
const warehouseDBColPath = 'warehouse_sites_master_data';
// Functional Area / Sub divisions/location/levels within the warehouse
const whStorageLocationDBColPath = 'warehouse_sublocation_master_data';
// Physical slot/position inside the location Sub divisions/levels
const whBinStorageDBColPath = 'warehouse_bin_master_data';
/// End Master-Data
///
const whInboundReceivingDBColPath = 'picking_shipments';
const whPickShipmentsDBColPath = 'wh_picking_shipments';
const whInternalMovementsDBColPath = 'wh_internal_movements';
// Invoices
const invoiceDBColPath = 'invoice_inventory_db';
// Items
const itemsDBColPath = 'items_inventory_db';
// Sales records
const salesDBColPath = 'sales_inventory_db';
// Delivery records
const deliveryDBColPath = 'delivery_inventory_db';
// Standard sales orders
const ordersDBColPath = 'so_orders_inventory_db';
// Miscellaneous/custom orders
const miscOrdersDBColPath = 'misc_orders_inventory_db';
// Purchase orders
const purchaseOrdersDBColPath = 'purchase_orders_inventory_db';
// Purchase requisition
const purchaseRequisitionDBColPath = 'purchase_requisition_inventory_db';
// Request for Quotation (Procurement: Supplier → Company)
const requestPriceQuoteDBColPath = 'request_price_quote_inventory_db';
// Quotation (Sales / Distribution: Company → Customer)
const salesQuotationDBColPath = 'sales_quotation_inventory_db';
const salesShippingDelDBColPath = 'sales_shipping_delivery_inventory_db';

// ---------------------------
// 💬 Live Customer Support Collections Path
// ---------------------------

// Workspaces live customer chat support
const liveChatSupportDBColPath = 'live_chat_support_db';

// ---------------------------
// ⚙️ Setup & Configuration Collections Path
// ---------------------------

// Associate agents with their clients
const agentClientsDBColPath = 'agents_clients_mapping_db';
// User guides/manuals and documentation
const userGuideDBColPath = 'user_guide_db';
// Employee accounts
const employeesDBColPath = 'employee_account_db';
// Tracking employees auth sessions
const employeeSessionLogsColPath = 'employee_session_logs';
// Company internal departments
const departmentsDBColPath = 'departments_db';
// Company store locations/branches (Multi-Locations Feature)
const storeLocationsDBColPath = 'store_branches';
// company tax rates
const taxesDBColPath = 'taxes_db';
// Company setup: logo, name, address, etc.
const companyInfoDBColPath = 'company_info_db';
// Item/product suppliers
const supplierDBColPath = 'item_suppliers_db';
// Item/product categories
const categoryDBColPath = 'item_categories_db';
// Variant Attributes
const attributeDBColPath = 'variant_attributes_db';

// ---------------------------
// 🧾 POS (Point of Sale) System Path
// ---------------------------

// POS sales records
const posSalesDBColPath = 'pos_sales_db';
// POS orders
const posOrdersDBColPath = 'pos_orders_db';

// ---------------------------
// 👥 Customer Relationship Management (CRM) Path
// ---------------------------

// Customer records
const customersDBColPath = 'customers_crm_db';

// Define filenames to skip while zipping(backup)
final skipFilesBeforeZip = {
  '$userAuthCache.hive',
  '$userAuthCache.lock',
  '$deviceInfoCache.hive',
  '$deviceInfoCache.lock',
  '$rolesDBColPath.hive',
  '$rolesDBColPath.lock',
  '$workspaceAccDBColPath.hive',
  '$workspaceAccDBColPath.lock',
  '$subscriptionDBColPath.hive',
  '$subscriptionDBColPath.lock',
};

// 🧾 ERP / Business Data Cache
const erpCacheBoxes = [
  // Core setup & master data
  employeesDBColPath,
  rolesDBColPath,
  employeeSessionLogsColPath,
  storeLocationsDBColPath,
  companyInfoDBColPath,
  departmentsDBColPath,
  supplierDBColPath,
  categoryDBColPath,
  attributeDBColPath,
  taxesDBColPath,

  // CRM
  customersDBColPath,

  // Inventory / Sales / Procurement
  itemMasterDBColPath,
  warehouseDBColPath,
  whStorageLocationDBColPath,
  whBinStorageDBColPath,
  itemsDBColPath,
  invoiceDBColPath,
  salesDBColPath,
  deliveryDBColPath,
  ordersDBColPath,
  miscOrdersDBColPath,
  purchaseOrdersDBColPath,
  purchaseRequisitionDBColPath,
  requestPriceQuoteDBColPath,
  salesQuotationDBColPath,
  salesShippingDelDBColPath,

  // POS
  posSalesDBColPath,
  posOrdersDBColPath,

  // Support & guides
  userGuideDBColPath,
  liveChatSupportDBColPath,

  // Agent / client mapping
  agentClientsDBColPath,
];

// ⚙️ System / App-Level Cache
const systemCacheBoxes = [
  // deviceInfoCache,
  // printoutSetupCache,
  backupFileNamesCache,
  refMasterCache,
  appErrorLogsCache,
];

// 🔐 Session / Auth Cache
const sessionCacheBoxes = [
  // userAuthCache,
  workspaceAccDBColPath,
  workspaceSessionLogsColPath,
];
