/// HIVE BOX CACHE NAMES
///
// Base Directory path for app-level cache files related to ERP assignment
const appCacheDirectory = 'loc_os_third_as_dir';

// Caches device information such as model, OS version, and unique identifiers
const deviceInfoCache = 'uos_device_info_cache_db';

// Stores the list of backup file names used or generated by the app
const backupFileNamesCache = 'backup_file_name_cache_db';

// Caches authenticated user credentials or ERP session info
const userAuthCache = 'os_auth_as_sign_erp_cache_db';

// Stores printout setup configuration like page layout or print preferences
const printoutSetupCache = 'setup_print_out_cache_db';

// Logs app errors or crash-related data for debugging
const appErrorLogsCache = 'app_error_logs_cache_db';

/// FIREBASE DATABASE COLLECTION NAMES & HIVE BOX TABLE NAMES

// ---------------------------
// 🔐 Authentication Collections
// ---------------------------

/// Firebase collection for workspace user authentication records
const workspaceAccDBCollectionPath = 'workspace_auth_db';
// Logs workspace signIn/signOut sessions for tracking and analytics
const workspaceSessionLogsCollectionPath = 'workspace_session_logs';

// ---------------------------
// 💰 Subscription Licenses Collections
// ---------------------------

/// Firebase collection for Subscription Licenses
const subscriptionDBCollectionPath = 'subscription_licenses_db';

// ---------------------------
// 🔐 Roles Collections
// ---------------------------

/// Firebase collection for employee's roles and permissions
const rolesDBCollectionPath = 'roles_db';

// ---------------------------
// 📦 Inventory Management System (IMS) Collections
// ---------------------------

/// Firebase collection for invoices
const invoiceDBCollectionPath = 'invoice_inventory_db';

/// Firebase collection for items
const itemsDBCollectionPath = 'items_inventory_db';

/// Firebase collection for sales records
const salesDBCollectionPath = 'sales_inventory_db';

/// Firebase collection for delivery records
const deliveryDBCollectionPath = 'delivery_inventory_db';

/// Firebase collection for standard sales orders
const ordersDBCollectionPath = 'so_orders_inventory_db';

/// Firebase collection for miscellaneous/custom orders
const miscOrdersDBCollectionPath = 'misc_orders_inventory_db';

/// Firebase collection for purchase orders
const purchaseOrdersDBCollectionPath = 'purchase_orders_inventory_db';

/// Firebase collection for purchase requisition
const purchaseRequisitionDBCollectionPath = 'purchase_requisition_inventory_db';

/// Firebase collection for customer price quote requests
const requestPriceQuoteDBCollectionPath = 'request_price_quote_inventory_db';

// ---------------------------
// 💬 Live Customer Support Collections
// ---------------------------

/// Firebase collection for Workspaces live customer chat support
const liveChatSupportDBCollectionPath = 'live_chat_support_db';

// ---------------------------
// ⚙️ Setup & Configuration Collections
// ---------------------------

/// Firebase Collection to associate agents with their clients
const agentClientsDBCollection = 'agents_clients_mapping_db';

/// Firebase collection for user guides/manuals and documentation
const userGuideDBCollectionPath = 'user_guide_db';

/// Firebase collection for employee accounts
const employeesDBCollectionPath = 'employee_account_db';
// for tracking employees auth sessions
const employeeSessionLogsCollectionPath = 'employee_session_logs';

/// Firebase collection for company departments
const departmentsDBCollectionPath = 'departments_db';

/// Firebase collection for company store locations/branches (Multi-Locations Feature)
const storeLocationsDBCollectionPath = 'store_locations_db';

/// Firebase collection for company tax rates
const taxesDBCollectionPath = 'taxes_db';

/// Firebase collection for general company information setup: logo, name, address, etc.
const companyInfoDBCollectionPath = 'company_info_db';

/// Firebase collection for item/product suppliers
const supplierDBCollectionPath = 'item_suppliers_db';

/// Firebase collection for item/product categories
const categoryDBCollectionPath = 'item_categories_db';

// ---------------------------
// 🧾 POS (Point of Sale) System
// ---------------------------

/// Firebase collection for POS sales records
const posSalesDBCollectionPath = 'pos_sales_db';

/// Firebase collection for POS orders
const posOrdersDBCollectionPath = 'pos_orders_db';

// ---------------------------
// 👥 Customer Relationship Management (CRM)
// ---------------------------

/// Firebase collection for customer records
const customersDBCollectionPath = 'customers_crm_db';
